# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db43c2767ca7ac8186b0119dc319ec03d6f8eddea238f192b6c9b431b2326183725f259d3efa8509c80bbddf8b0a5ad8c111b57ce9b24373a06e63e46159e6cc

test:
  secret_key_base: b89b1c3b35609021019c58f9c4b74e29c6e0dbbba9af3bb1097695f75325792a5a6c8a19841f2dc6d150112fb8c3125b74d751a29c9feda369d0546706799a86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
